# Problem 1 (5 points)

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Sigmoid function

Define a function, `sigmoid(h)`, which computes and returns the sigmoid `g(h)` given an input `h`.
Recall the mathematical formulation of sigmoid:
$$ g(h) = \frac{1}{1+e^{-h}}$$

In [2]:
def sigmoid(h):
    # YOUR CODE GOES HERE    
    return 1/(1+np.exp(-h))

## Transformation function
In logistic regression, we transform the input before applying the sigmoid function. This transformation can take many forms, but here let's define a function `transform_quadratic(x,w)` that takes in an input `x`, and a weight vector `w`, and returns the sum $ w_0 \cdot 1 + w_1 \cdot x + w_2 \cdot x^2 $.

In [3]:
def transform_quadratic(x, w):
    # YOUR CODE GOES HERE
    # input x is a 1D data point
    # input w is a row vector 
    x = np.array([x**(3-i) for i in range(1,4)]).reshape(-1,1)
    w = np.array(w).reshape(1,-1)
    return  x @ w 


## Example

Now, we will use both `sigmoid()` and `transform_quadratic()` in a logistic regression context.

Suppose a logistic regression model states that:
$$P(y=1\;|\;x) = g(\textbf{w}'x),$$
for $g(h)$ the sigmoid function and $\textbf{w} = [4, -3, 2]$.

Use the functions you wrote to compute $P(y=1\;|\;x=1.2)$ and $P(y=1\;|\;x=7)$. Print these probabilities.

In [4]:
w = [4,-3,2]
for x in [1.2, 7.]:
    P = sigmoid(transform_quadratic(x,w))
    print(f"x = {x:3} --> P(y=1) = {P}")

x = 1.2 --> P(y=1) = [[0.99685879 0.01312532 0.94684886]
 [0.99183743 0.02659699 0.9168273 ]
 [0.98201379 0.04742587 0.88079708]]
x = 7.0 --> P(y=1) = [[1.00000000e+00 1.44115655e-64 1.00000000e+00]
 [1.00000000e+00 7.58256042e-10 9.99999168e-01]
 [9.82013790e-01 4.74258732e-02 8.80797078e-01]]
